config/routes.rb
Rails.application.routes.draw do
  get 'offers/index'

  get 'offers/new'

  get 'offers/create'

  get 'offers/destroy'

  #cuando pinchas en el boton
  post 'offers/stats'

  resources :offers

  root to: "offers#index"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
#para cargarla desde el crawler
require 'mongoid'

class Offer
  include Mongoid::Document
  field :nombre_oferta, type: String
  field :nombre_empresa, type: String
  field :localizacion, type: String
  field :descrp_oferta, type: String
  field :responsabilidad, type: String
  field :tipo_jornada, type: String
  field :experiencia, type: String


  def initialize( oferta, empresa, localizacion, desc, experiencia )
    @nombre_oferta = oferta
    @nombre_empresa = empresa
    @localizacion = localizacion
    @descrp_oferta = desc
    @experiencia = experiencia
  end

  def getOferta
  	@nombre_oferta
  end

  def getEmpresa
  	@nombre_empresa
  end

  # Getters y Setters ...

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/infoEmpleoCrawler.rb
# CONJUNTO de métodos para crawlear infoEmpleo con Nokigiri

require 'open-uri'
require 'nokogiri'
require './app/models/offer.rb'

def getNombreOferta(doc, list)

  		@doc.xpath("//h2//a").each do |link|
  			list << (link.content)
  		end
end


def getNombreEmpresa(doc, list)
	filtrador = 0

	@doc.xpath('//li//p[contains(@class, "block")]').each do |link|
		if filtrador == 0
			list << (link.content)
		elsif filtrador == 2
			filtrador = 0
			next
		end
		filtrador += 1
	end
end

def getLocalizacion(doc, list)
	filtrador = 0

	@doc.xpath('//li//p[contains(@class, "block")]').each do |link|
		if filtrador == 1
			list << (link.content)
		elsif filtrador == 2
			filtrador = 0
			next
		end
		filtrador += 1
	end
end

def getDescripcion(doc, list)
  		@doc.xpath('//li//p[contains(@class, "description")]').each do |link|
  			list << (link.content)
  		end
end

def getExperiencia(doc, list)
  		@doc.xpath('//li//p[contains(@class, "small")]').each do |link|
  			list << (link.content)
  		end
end

def toOfertas(doc, list)
	nombres = Array.new
	empresas = Array.new
	localizaciones = Array.new
	descriptions = Array.new
	experiencias = Array.new

	getNombreOferta(doc, nombres)
	getNombreEmpresa(doc, empresas)
	getLocalizacion(doc, localizaciones)
	getDescripcion(doc, descriptions)
	getExperiencia(doc, experiencias)

	ofertas = Array.new

	contador = 0

	while contador < nombres.size do

		nombre = nombres[contador]
		empresa = empresas[contador]
		loc = localizaciones[contador]
		des = descriptions[contador]
		exp = experiencias[contador]

		offer = Offer.new(nombre, empresa, loc, des, exp)

		list << offer

		contador +=1

	end

end

def getAllPagesInfoEmpleo(numPaginas, ofertasTotales)

	pagina = 1

	@doc = Nokogiri::HTML(open("http://www.infoempleo.com/trabajo/"))


	while pagina <= numPaginas do
		if pagina <= 1
			toOfertas(@doc,ofertasTotales)
		else
			@doc2 = Nokogiri::HTML(open("http://www.infoempleo.com/trabajo/pagina_#{pagina}"))
			toOfertas(@doc2,ofertasTotales)
		end

		pagina +=1

	end


end


# estas líneas son para probar, quitarlas si es preciso:

prueba = Array.new

getAllPagesInfoEmpleo(2, prueba)

prueba.each do |offer|
	puts offer.getOferta
#--------------------------------------------------------
end

app/controllers/offers_controller.rb
require 'infoEmpleoCrawler'

class OffersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end

  def stats

  	@ofertasInfoEmpleo = Array.new

  	getAllPagesInfoEmpleo(2, @ofertasInfoEmpleo)

  	@sizeInforEmpleo = @ofertasInfoEmpleo.length

  end

  #esto esta siendo un metodo de prueba de momento
  helper_method :integrateOffers

  def integrateOffers
  	prueba = Array.new

	getAllPagesInfoEmpleo(2, prueba)

	prueba.each do |offer|
		puts offer.getOferta
	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crauler</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/offers/create.html.erb
<h1>Offers#create</h1>
<p>Find me in app/views/offers/create.html.erb</p>

app/views/offers/destroy.html.erb
<h1>Offers#destroy</h1>
<p>Find me in app/views/offers/destroy.html.erb</p>

app/views/offers/index.html.erb
<h1>Ofertas</h1>
<p>Ejecutar proceso</p>

<%= button_to "Iniciar", offers_stats_path, :method=> "stats" %>

app/views/offers/new.html.erb
<h1>Offers#new</h1>
<p>Find me in app/views/offers/new.html.erb</p>

app/views/offers/stats.html.erb
    <h1>Número de ofertas</h1>
    <h3><%= @sizeInforEmpleo%></h3>
   	
    